import { Contact, Cap } from "../types/campaign";

export const EMAILCAMPAIGN_INITIAL = {
  EmailCampaignId: 0,
  Title: "",
  Object: "",
  Description: "",
};

export const WHATSAPPCAMPAIGN_INITIAL = {
  WhatsappCampaignId: 0,
  Title: "",
  Description: "",
};

export const contacts: Contact[] = [
  { code: "215", name: "Savino Depalma" },
  { code: "217", name: "Francesco Pontrelli" },
  { code: "218", name: "Giorgio Fabris" },
  { code: "788", name: "Federico Micozzi" },
  { code: "1216", name: "Francesco Poli" },
  { code: "6146", name: "Andrzej Rygiewicz" },
  { code: "6299", name: "Davide Voltarelli" },
  { code: "31075", name: "Thomas Garcia" },
  { code: "31082", name: "Niccolò Varisco" },
  { code: "10877", name: "Paolo Bernini" },
  { code: "10766", name: "Chiara Semprepiovi" },
  { code: "2346", name: "Letizia Depalma" },
  { code: "6366", name: "Maria Vittoria Pontrelli" },
  { code: "31083", name: "Ilaria Cellai" },
  { code: "10803", name: "Diletta Pontrelli" }

];



export const tuscanyCaps: Cap[] = [
  // FIRENZE E PROVINCIA
  // CAP Generale
  { Cap: "50100", City: "Firenze - Generale" },
  
  // CAP specifici Firenze città
  { Cap: "50121", City: "Firenze - Centro Storico, Piazza Signoria" },
  { Cap: "50122", City: "Firenze - Santa Croce, Uffizi" },
  { Cap: "50123", City: "Firenze - Santo Spirito, San Frediano" },
  { Cap: "50124", City: "Firenze - Isolotto, Legnaia" },
  { Cap: "50125", City: "Firenze - Gavinana, Galluzzo" },
  { Cap: "50126", City: "Firenze - Bandino, Spedaluzzo" },
  { Cap: "50127", City: "Firenze - Novoli, Peretola" },
  { Cap: "50128", City: "Firenze - Cascine, Rifredi" },
  { Cap: "50129", City: "Firenze - Campo di Marte, Cure" },
  { Cap: "50130", City: "Firenze - Settignano, Rovezzano" },
  { Cap: "50131", City: "Firenze - Careggi, Trespiano" },
  { Cap: "50132", City: "Firenze - Coverciano, Campo di Marte" },
  { Cap: "50133", City: "Firenze - Le Cure, San Domenico" },
  { Cap: "50134", City: "Firenze - Viale Europa, Badia a Ripoli" },
  { Cap: "50135", City: "Firenze - Statuto, Fortezza" },
  { Cap: "50136", City: "Firenze - Rifredi, Careggi" },
  { Cap: "50137", City: "Firenze - Novoli, Castello" },
  { Cap: "50138", City: "Firenze - San Jacopino, Porta al Prato" },
  { Cap: "50139", City: "Firenze - Castello, Serpiolle" },
  { Cap: "50140", City: "Firenze - Brozzi, Quaracchi" },
  { Cap: "50141", City: "Firenze - Le Piagge, San Donnino" },
  { Cap: "50142", City: "Firenze - Isolotto, Torri" },
  { Cap: "50143", City: "Firenze - Mantignano, Ugnano" },
  { Cap: "50144", City: "Firenze - Porta al Prato, Cascine" },
  { Cap: "50145", City: "Firenze - Novoli, Firenze Nova" },

  // Area metropolitana di Firenze
  { Cap: "50010", City: "Firenze - Antella" },
  { Cap: "50011", City: "Firenze - Compiobbi" },
  { Cap: "50012", City: "Bagno a Ripoli" },
  { Cap: "50013", City: "Campi Bisenzio" },
  { Cap: "50014", City: "Fiesole" },
  { Cap: "50015", City: "Firenze - Grassina" },
  { Cap: "50016", City: "Firenze - Londa" },
  { Cap: "50017", City: "Firenze - Montespertoli" },
  { Cap: "50018", City: "Scandicci" },
  { Cap: "50019", City: "Sesto Fiorentino" },
  { Cap: "50020", City: "Firenze - Pian di San Bartolo" },
  { Cap: "50021", City: "Firenze - Barberino Val d'Elsa" },
  { Cap: "50022", City: "Greve in Chianti" },
  { Cap: "50023", City: "Firenze - Impruneta" },
  { Cap: "50024", City: "Firenze - Mercatale Val di Pesa" },
  { Cap: "50025", City: "Firenze - Montespertoli" },
  { Cap: "50026", City: "San Casciano Val di Pesa" },
  { Cap: "50027", City: "Firenze - Strada in Chianti" },
  { Cap: "50028", City: "Firenze - Tavarnuzze" },
  { Cap: "50029", City: "Firenze - Tavarnelle Val di Pesa" },
  { Cap: "50030", City: "Firenze - Vaglia" },
  { Cap: "50031", City: "Firenze - Barberino di Mugello" },
  { Cap: "50032", City: "Firenze - Borgo San Lorenzo" },
  { Cap: "50033", City: "Firenze - Firenzuola" },
  { Cap: "50034", City: "Firenze - Marradi" },
  { Cap: "50035", City: "Firenze - Palazzuolo sul Senio" },
  { Cap: "50036", City: "Firenze - Pratolino" },
  { Cap: "50037", City: "Firenze - San Piero a Sieve" },
  { Cap: "50038", City: "Firenze - Scarperia" },
  { Cap: "50039", City: "Firenze - Vicchio" },
  { Cap: "50041", City: "Calenzano" },
  { Cap: "50050", City: "Firenze - Limite sull'Arno" },

  // PISTOIA E PROVINCIA
  // CAP Generale
  { Cap: "51100", City: "Pistoia - Generale" },
  
  // CAP specifici provincia di Pistoia
  { Cap: "51010", City: "Pistoia - Uzzano" },
  { Cap: "51011", City: "Pistoia - Buggiano" },
  { Cap: "51012", City: "Pistoia - Pescia" },
  { Cap: "51013", City: "Pistoia - Chiesina Uzzanese" },
  { Cap: "51014", City: "Pistoia - Valdinievole" },
  { Cap: "51015", City: "Pistoia - Monsummano Terme" },
  { Cap: "51016", City: "Pistoia - Montecatini Terme" },
  { Cap: "51017", City: "Pistoia - Pescia" },
  { Cap: "51018", City: "Pistoia - Pieve a Nievole" },
  { Cap: "51019", City: "Pistoia - Ponte Buggianese" },
  { Cap: "51020", City: "Pistoia - San Momme" },
  { Cap: "51021", City: "Pistoia - Marliana" },
  { Cap: "51022", City: "Pistoia - Bagni di Lucca" },
  { Cap: "51023", City: "Pistoia - Campo Tizzoro" },
  { Cap: "51024", City: "Pistoia - Cutigliano" },
  { Cap: "51025", City: "Pistoia - Abetone" },
  { Cap: "51026", City: "Pistoia - San Marcello Pistoiese" },
  { Cap: "51027", City: "Pistoia - Passo della Collina" },
  { Cap: "51028", City: "Pistoia - San Marcello Piteglio" },
  { Cap: "51029", City: "Pistoia - Vernio" },
  { Cap: "51030", City: "Pistoia - Marliana" },
  { Cap: "51031", City: "Pistoia - Agliana" },
  { Cap: "51032", City: "Pistoia - Bottegone" },
  { Cap: "51033", City: "Pistoia - Cantagrillo" },
  { Cap: "51034", City: "Pistoia - Casalguidi" },
  { Cap: "51035", City: "Pistoia - Lamporecchio" },
  { Cap: "51036", City: "Pistoia - Larciano" },
  { Cap: "51037", City: "Pistoia - Montale" },
  { Cap: "51038", City: "Pistoia - Quarrata" },
  { Cap: "51039", City: "Pistoia - Quarrata" },

  // PRATO E PROVINCIA
  // CAP Generale
  { Cap: "59100", City: "Prato - Generale" },
  
  // CAP specifici provincia di Prato
  { Cap: "59011", City: "Prato - Artimino" },
  { Cap: "59012", City: "Prato - Galciana" },
  { Cap: "59013", City: "Prato - Montemurlo" },
  { Cap: "59014", City: "Prato - Carmignano" },
  { Cap: "59015", City: "Prato - Comeana" },
  { Cap: "59016", City: "Prato - Poggio a Caiano" },
  { Cap: "59017", City: "Prato - Vaiano" },
  { Cap: "59018", City: "Prato - Vernio" },
  { Cap: "59019", City: "Prato - Seano" },
  { Cap: "59021", City: "Prato - Vaiano" },
  { Cap: "59022", City: "Prato - Pratolino" },
  { Cap: "59023", City: "Prato - Mercatale di Vernio" },
  { Cap: "59024", City: "Prato - San Giusto" },
  { Cap: "59025", City: "Prato - Usella" },
  { Cap: "59026", City: "Prato - Usella" },
  { Cap: "59027", City: "Prato - Vernio" },
  { Cap: "59028", City: "Prato - La Briglia" },
  { Cap: "59029", City: "Prato - Vaiano" },

  // PISA E PROVINCIA
  // CAP Generale
  { Cap: "56100", City: "Pisa - Generale" },
  
  // CAP specifici Pisa città
  { Cap: "56121", City: "Pisa - Centro storico" },
  { Cap: "56122", City: "Pisa - Sant'Antonio, Porta a Lucca" },
  { Cap: "56123", City: "Pisa - San Martino, San Giusto" },
  { Cap: "56124", City: "Pisa - Don Bosco, Pratale" },
  { Cap: "56125", City: "Pisa - Cisanello, San Biagio" },
  { Cap: "56126", City: "Pisa - Ospedaletto, Riglione" },
  { Cap: "56127", City: "Pisa - Barbaricina, CEP" },
  { Cap: "56128", City: "Pisa - Porta a Mare, Calabrone" },

  // SIENA E PROVINCIA
  // CAP Generale
  { Cap: "53100", City: "Siena - Generale" },
  
  // CAP specifici provincia di Siena
  { Cap: "53011", City: "Siena - Castellina in Chianti" },
  { Cap: "53012", City: "Siena - Chiusdino" },
  { Cap: "53013", City: "Siena - Gaiole in Chianti" },
  { Cap: "53014", City: "Siena - Monteroni d'Arbia" },
  { Cap: "53015", City: "Siena - Monticiano" },
  { Cap: "53016", City: "Siena - Murlo" },
  { Cap: "53017", City: "Siena - Radda in Chianti" },
  { Cap: "53018", City: "Siena - Sovicille" },
  { Cap: "53019", City: "Siena - Castelnuovo Berardenga" },
  { Cap: "53020", City: "Siena - San Giovanni d'Asso" },
  { Cap: "53021", City: "Siena - Abbadia San Salvatore" },
  { Cap: "53022", City: "Siena - Buonconvento" },
  { Cap: "53023", City: "Siena - Castiglione d'Orcia" },
  { Cap: "53024", City: "Siena - Montalcino" },
  { Cap: "53025", City: "Siena - Piancastagnaio" },
  { Cap: "53026", City: "Siena - Pienza" },
  { Cap: "53027", City: "Siena - San Quirico d'Orcia" },
  { Cap: "53028", City: "Siena - Torrenieri" },
  { Cap: "53029", City: "Siena - Trevinano" },
  { Cap: "53030", City: "Siena - Radicondoli" },
  { Cap: "53031", City: "Siena - Casole d'Elsa" },
  { Cap: "53034", City: "Siena - Colle di Val d'Elsa" },
  { Cap: "53035", City: "Siena - Monteriggioni" },
  { Cap: "53036", City: "Siena - Poggibonsi" },
  { Cap: "53037", City: "Siena - San Gimignano" },
  { Cap: "53038", City: "Siena - Val d'Elsa" },
  { Cap: "53039", City: "Siena - Val d'Elsa" },
  { Cap: "53040", City: "Siena - Radicofani" },
  { Cap: "53041", City: "Siena - Asciano" },
  { Cap: "53042", City: "Siena - Chianciano Terme" },
  { Cap: "53043", City: "Siena - Chiusi" },
  { Cap: "53044", City: "Siena - Chiusi Scalo" },
  { Cap: "53045", City: "Siena - Montepulciano" },
  { Cap: "53046", City: "Siena - Sinalunga" },
  { Cap: "53047", City: "Siena - Sarteano" },
  { Cap: "53048", City: "Siena - Sinalunga" },
  { Cap: "53049", City: "Siena - Torrita di Siena" },

  // GROSSETO E PROVINCIA
  // CAP Generale
  { Cap: "58100", City: "Grosseto - Generale" },
  
  // CAP specifici provincia di Grosseto
  { Cap: "58010", City: "Grosseto - Sorano" },
  { Cap: "58011", City: "Grosseto - Capalbio" },
  { Cap: "58012", City: "Grosseto - Isola del Giglio" },
  { Cap: "58013", City: "Grosseto - Monterotondo Marittimo" },
  { Cap: "58014", City: "Grosseto - Manciano" },
  { Cap: "58015", City: "Grosseto - Orbetello" },
  { Cap: "58016", City: "Grosseto - Montemerano" },
  { Cap: "58017", City: "Grosseto - Pitigliano" },
  { Cap: "58018", City: "Grosseto - Porto Ercole" },
  { Cap: "58019", City: "Grosseto - Porto Santo Stefano" },
  { Cap: "58020", City: "Grosseto - Scarlino" },
  { Cap: "58021", City: "Grosseto - Bagnolo" },
  { Cap: "58022", City: "Grosseto - Follonica" },
  { Cap: "58023", City: "Grosseto - Gavorrano" },
  { Cap: "58024", City: "Grosseto - Massa Marittima" },
  { Cap: "58025", City: "Grosseto - Monterotondo Marittimo" },
  { Cap: "58026", City: "Grosseto - Montieri" },
  { Cap: "58027", City: "Grosseto - Ribolla" },
  { Cap: "58028", City: "Grosseto - Roccatederighi" },
  { Cap: "58029", City: "Grosseto - Sassetta" },
  { Cap: "58030", City: "Grosseto - Ravi" },
  { Cap: "58031", City: "Grosseto - Arcidosso" },
  { Cap: "58032", City: "Grosseto - Stribugliano" },
  { Cap: "58033", City: "Grosseto - Castel del Piano" },
  { Cap: "58034", City: "Grosseto - Castell'Azzara" },
  { Cap: "58035", City: "Grosseto - Monticello Amiata" },
  { Cap: "58036", City: "Grosseto - Roccastrada" },
  { Cap: "58037", City: "Grosseto - Santa Fiora" },
  { Cap: "58038", City: "Grosseto - Seggiano" },
  { Cap: "58039", City: "Grosseto - Semproniano" },
  { Cap: "58040", City: "Grosseto - Civitella Paganico" },
  { Cap: "58041", City: "Grosseto - Campagnatico" },
  { Cap: "58042", City: "Grosseto - Campagnatico" },
  { Cap: "58043", City: "Grosseto - Castiglione della Pescaia" },
  { Cap: "58044", City: "Grosseto - Cinigiano" },
  { Cap: "58045", City: "Grosseto - Civitella Paganico" },
  { Cap: "58046", City: "Grosseto - Marina di Grosseto" },
  { Cap: "58047", City: "Grosseto - Paganico" },
  { Cap: "58048", City: "Grosseto - Paganico" },
  { Cap: "58049", City: "Grosseto - Scansano" },

  // LIVORNO E PROVINCIA
  // CAP Generale
  { Cap: "57100", City: "Livorno - Generale" },
  
  // CAP specifici Livorno città
  { Cap: "57121", City: "Livorno - Centro" },
  { Cap: "57122", City: "Livorno - Ardenza, Antignano" },
  { Cap: "57123", City: "Livorno - Scopaia, Leccia" },
  { Cap: "57124", City: "Livorno - Sorgenti, Corea" },
  { Cap: "57125", City: "Livorno - Coteto, Collinaia" },
  { Cap: "57126", City: "Livorno - La Rosa, Salviano" },
  { Cap: "57127", City: "Livorno - Montenero, Castellaccio" },
  { Cap: "57128", City: "Livorno - Quercianella, Chioma" },

  // CAP specifici provincia di Livorno
  { Cap: "57014", City: "Livorno - Collesalvetti" },
  { Cap: "57016", City: "Livorno - Rosignano Marittimo" },
  { Cap: "57017", City: "Livorno - Collesalvetti" },
  { Cap: "57018", City: "Livorno - Vada" },
  { Cap: "57019", City: "Livorno - Vicarello" },
  { Cap: "57020", City: "Livorno - Bibbona" },
  { Cap: "57021", City: "Livorno - Campiglia Marittima" },
  { Cap: "57022", City: "Livorno - Castagneto Carducci" },
  { Cap: "57023", City: "Livorno - Cecina" },
  { Cap: "57024", City: "Livorno - Donoratico" },
  { Cap: "57025", City: "Livorno - Piombino" },
  { Cap: "57026", City: "Livorno - Piombino" },
  { Cap: "57027", City: "Livorno - San Vincenzo" },
  { Cap: "57028", City: "Livorno - Suvereto" },
  { Cap: "57029", City: "Livorno - Venturina" },
  { Cap: "57030", City: "Livorno - Marciana" },
  { Cap: "57031", City: "Livorno - Capoliveri" },
  { Cap: "57032", City: "Livorno - Capraia Isola" },
  { Cap: "57033", City: "Livorno - Marciana Marina" },
  { Cap: "57034", City: "Livorno - Marina di Campo" },
  { Cap: "57035", City: "Livorno - Marina di Campo" },
  { Cap: "57036", City: "Livorno - Porto Azzurro" },
  { Cap: "57037", City: "Livorno - Portoferraio" },
  { Cap: "57038", City: "Livorno - Rio Marina" },
  { Cap: "57039", City: "Livorno - Rio nell'Elba" },

  // MASSA-CARRARA E PROVINCIA
  // CAP Generale
  { Cap: "54100", City: "Massa - Generale" },
  
  // CAP specifici provincia di Massa-Carrara
  { Cap: "54011", City: "Massa - Aulla" },
  { Cap: "54013", City: "Massa - Fivizzano" },
  { Cap: "54014", City: "Massa - Casola in Lunigiana" },
  { Cap: "54015", City: "Massa - Comano" },
  { Cap: "54016", City: "Massa - Licciana Nardi" },
  { Cap: "54017", City: "Massa - Montignoso" },
  { Cap: "54018", City: "Massa - Marina di Massa" },
  { Cap: "54019", City: "Massa - Marina di Carrara" },
  { Cap: "54020", City: "Massa - Montignoso" },
  { Cap: "54021", City: "Massa - Bagnone" },
  { Cap: "54022", City: "Massa - Mulazzo" },
  { Cap: "54023", City: "Massa - Filattiera" },
  { Cap: "54024", City: "Massa - Licciana Nardi" },
  { Cap: "54025", City: "Massa - Mulazzo" },
  { Cap: "54026", City: "Massa - Pontremoli" },
  { Cap: "54027", City: "Massa - Pontremoli" },
  { Cap: "54028", City: "Massa - Villafranca in Lunigiana" },
  { Cap: "54029", City: "Massa - Zeri" },
  { Cap: "54030", City: "Massa - Casola in Lunigiana" },
  { Cap: "54031", City: "Massa - Avenza" },
  { Cap: "54033", City: "Massa - Carrara" },
  { Cap: "54035", City: "Massa - Fosdinovo" },
  { Cap: "54036", City: "Massa - Marina di Carrara" },
  { Cap: "54037", City: "Massa - Marina di Massa" },
  { Cap: "54038", City: "Massa - Montignoso" },
  { Cap: "54039", City: "Massa - Tresana" },

  // LUCCA E PROVINCIA
  // CAP Generale
  { Cap: "55100", City: "Lucca - Generale" },
  
  // CAP specifici provincia di Lucca
  { Cap: "55011", City: "Lucca - Altopascio" },
  { Cap: "55012", City: "Lucca - Capannori" },
  { Cap: "55013", City: "Lucca - Lammari" },
  { Cap: "55014", City: "Lucca - Marlia" },
  { Cap: "55015", City: "Lucca - Montecarlo" },
  { Cap: "55016", City: "Lucca - Porcari" },
  { Cap: "55017", City: "Lucca - San Salvatore" },
  { Cap: "55018", City: "Lucca - Segromigno in Monte" },
  { Cap: "55019", City: "Lucca - Villa Basilica" },
  { Cap: "55020", City: "Lucca - Borgo a Mozzano" },
  { Cap: "55021", City: "Lucca - Bagni di Lucca" },
  { Cap: "55022", City: "Lucca - Bagni di Lucca" },
  { Cap: "55023", City: "Lucca - Borgo a Mozzano" },
  { Cap: "55024", City: "Lucca - Ponte all'Ania" },
  { Cap: "55025", City: "Lucca - Coreglia Antelminelli" },
  { Cap: "55026", City: "Lucca - Fornaci di Barga" },
  { Cap: "55027", City: "Lucca - Gallicano" },
  { Cap: "55028", City: "Lucca - Piano di Coreglia" },
  { Cap: "55029", City: "Lucca - Ponte a Moriano" },
  { Cap: "55030", City: "Lucca - Barga" },
  { Cap: "55031", City: "Lucca - Camporgiano" },
  { Cap: "55032", City: "Lucca - Castelnuovo di Garfagnana" },
  { Cap: "55033", City: "Lucca - Castiglione di Garfagnana" },
  { Cap: "55034", City: "Lucca - Minucciano" },
  { Cap: "55035", City: "Lucca - Piazza al Serchio" },
  { Cap: "55036", City: "Lucca - Pieve Fosciana" },
  { Cap: "55037", City: "Lucca - San Romano in Garfagnana" },
  { Cap: "55038", City: "Lucca - Villa Collemandina" },
  { Cap: "55039", City: "Lucca - Vagli Sotto" },
  { Cap: "55040", City: "Lucca - Pescaglia" },
  { Cap: "55041", City: "Lucca - Camaiore" },
  { Cap: "55042", City: "Lucca - Forte dei Marmi" },
  { Cap: "55043", City: "Lucca - Lido di Camaiore" },
  { Cap: "55044", City: "Lucca - Marina di Pietrasanta" },
  { Cap: "55045", City: "Lucca - Pietrasanta" },
  { Cap: "55046", City: "Lucca - Querceta" },
  { Cap: "55047", City: "Lucca - Seravezza" },
  { Cap: "55048", City: "Lucca - Torre del Lago Puccini" },
  { Cap: "55049", City: "Lucca - Viareggio" },
  { Cap: "55050", City: "Lucca - Balbano" },
  { Cap: "55051", City: "Lucca - Barga" },

  // AREZZO E PROVINCIA
  // CAP Generale
  { Cap: "52100", City: "Arezzo - Generale" },
  
  // CAP specifici provincia di Arezzo
  { Cap: "52010", City: "Arezzo - Chiusi della Verna" },
  { Cap: "52011", City: "Arezzo - Bibbiena" },
  { Cap: "52012", City: "Arezzo - Civitella in Val di Chiana" },
  { Cap: "52013", City: "Arezzo - Ponte alla Chiassa" },
  { Cap: "52014", City: "Arezzo - Poppi" },
  { Cap: "52015", City: "Arezzo - Pratovecchio" },
  { Cap: "52016", City: "Arezzo - Castiglion Fiorentino" },
  { Cap: "52017", City: "Arezzo - Stia" },
  { Cap: "52018", City: "Arezzo - Corsalone" },
  { Cap: "52019", City: "Arezzo - Laterina" },
  { Cap: "52020", City: "Arezzo - Laterina" },
  { Cap: "52021", City: "Arezzo - Bucine" },
  { Cap: "52022", City: "Arezzo - Cavriglia" },
  { Cap: "52023", City: "Arezzo - Levane" },
  { Cap: "52024", City: "Arezzo - Loro Ciuffenna" },
  { Cap: "52025", City: "Arezzo - Montevarchi" },
  { Cap: "52026", City: "Arezzo - Pian di Scò" },
  { Cap: "52027", City: "Arezzo - San Giovanni Valdarno" },
  { Cap: "52028", City: "Arezzo - Terranuova Bracciolini" },
  { Cap: "52029", City: "Arezzo - Castiglion Fibocchi" },
  { Cap: "52030", City: "Arezzo - Chitignano" },
  { Cap: "52031", City: "Arezzo - Anghiari" },
  { Cap: "52032", City: "Arezzo - Badia Tedalda" },
  { Cap: "52033", City: "Arezzo - Caprese Michelangelo" },
  { Cap: "52034", City: "Arezzo - Ortignano Raggiolo" },
  { Cap: "52035", City: "Arezzo - Monterchi" },
  { Cap: "52036", City: "Arezzo - Pieve Santo Stefano" },
  { Cap: "52037", City: "Arezzo - Sansepolcro" },
  { Cap: "52038", City: "Arezzo - Sestino" },
  { Cap: "52039", City: "Arezzo - Talla"},
  { Cap: "52038", City: "Arezzo - Sestino" },
  { Cap: "52039", City: "Arezzo - Talla" },
  { Cap: "52040", City: "Arezzo - Chiassaia" },
  { Cap: "52041", City: "Arezzo - Badia Agnano" },
  { Cap: "52042", City: "Arezzo - Camucia" },
  { Cap: "52043", City: "Arezzo - Castiglion Fiorentino" },
  { Cap: "52044", City: "Arezzo - Cortona" },
  { Cap: "52045", City: "Arezzo - Foiano della Chiana" },
  { Cap: "52046", City: "Arezzo - Lucignano" },
  { Cap: "52047", City: "Arezzo - Marciano della Chiana" },
  { Cap: "52048", City: "Arezzo - Monte San Savino" },
  { Cap: "52049", City: "Arezzo - Torrita di Siena" }
];




